export const getUuidCode = ():string => {
    //64长度
    let len:number = 128;
    let rando:Array<string> = [
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "#",
        "$",
        "%",
        "&",
        "*",
        "+",
        "-",
        "/",
        "=",
        "?",
        "@",
        "^",
        "_",
        "~",
    ];
    let uuid:string = "";
    for (let i = 0; i < len; i++) {
        let index: number = Math.floor(Math.random() * 77);
        uuid += rando[index];
    }
    return uuid;
}